INSERT INTO TREE_SYNC (ID, EXIST_ONPC, EXIST_ON_PHONE, NAME, RELATIVE_PATH) VALUES (1, true, true, '\', '\');

INSERT INTO FOLDER_SYNC (ID, EXIST_ONPC, EXIST_ON_PHONE, NAME, RELATIVE_PATH, PARENT_ID) VALUES (2, true, true, 'Music Folder1', '\\Music Folder1', 1);
INSERT INTO FOLDER_SYNC (ID, EXIST_ONPC, EXIST_ON_PHONE, NAME, RELATIVE_PATH, PARENT_ID) VALUES (3, true, true, 'Music Folder2', '\\Music Folder2', 1);

INSERT INTO FILE_SYNC (ID, EXIST_ONPC, EXIST_ON_PHONE, NAME, RELATIVE_PATH, PARENT_ID) VALUES (4, true, true, 'Composition 1', '\\Music Folder1\Composition 1', 2);
INSERT INTO FILE_SYNC (ID, EXIST_ONPC, EXIST_ON_PHONE, NAME, RELATIVE_PATH, PARENT_ID) VALUES (5, true, false, 'Composition 2', '\\Music Folder1\Composition 2', 2);
INSERT INTO FILE_SYNC (ID, EXIST_ONPC, EXIST_ON_PHONE, NAME, RELATIVE_PATH, PARENT_ID) VALUES (6, true, true, 'Composition 3', '\\Music Folder1\Composition 3', 2);

INSERT INTO FILE_SYNC (ID, EXIST_ONPC, EXIST_ON_PHONE, NAME, RELATIVE_PATH, PARENT_ID) VALUES (7, true, true, 'Composition 1', '\\Music Folder2\Composition 1', 3);
INSERT INTO FILE_SYNC (ID, EXIST_ONPC, EXIST_ON_PHONE, NAME, RELATIVE_PATH, PARENT_ID) VALUES (8, true, true, 'Composition 2', '\\Music Folder2\Composition 2', 3);
INSERT INTO FILE_SYNC (ID, EXIST_ONPC, EXIST_ON_PHONE, NAME, RELATIVE_PATH, PARENT_ID) VALUES (9, true, true, 'Composition 3', '\\Music Folder2\Composition 3', 3);
